/*
 * endian.h
 *
 *  Created on: 21 déc. 2018
 *      Author: thomas
 */

#ifndef THIRD_PARTY_MCUBOOT_BOOT_STM32_INCLUDE_OS_ENDIAN_H_
#define THIRD_PARTY_MCUBOOT_BOOT_STM32_INCLUDE_OS_ENDIAN_H_





#endif /* THIRD_PARTY_MCUBOOT_BOOT_STM32_INCLUDE_OS_ENDIAN_H_ */
